name = "jiaxiang.wang"
description = "A fast and beautiful theme for creators, used by https://blog.jiaxiang.wang, porting from Halo-theme-hao, originally designed by https://blog.zhheo.com/"
license = "AGPL"
homepage = "https://github.com/iWangJiaxiang/zola-theme-jiaxiang.wang"
min_version = "0.19.2"
demo = "https://blog.jiaxiang.wang/"

[author]
name = "Jiaxiang Wang"
homepage = "https://blog.jiaxiang.wang"

[extra]