name = "jiaxiang.wang"
description = "A fast and beautiful theme for creators, used by https://blog.jiaxiang.wang, porting from Halo-theme-hao."
license = "AGPL"
homepage = "https://github.com/iWangJiaxiang/zola-theme-jiaxiang.wang"
min_version = "0.19.2"
demo = "https://theme.jiaxiang.wang/"

[author]
name = "Jiaxiang Wang"
homepage = "https://blog.jiaxiang.wang"

[original]
author =  "chengzhongxue"
homepage = "https://github.com/chengzhongxue"
repo = "https://github.com/chengzhongxue/halo-theme-hao"

[extra]