name: Build Search Index
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      # 内容更新
      - content/**
      # 配置更新
      - meilisearch-docs-scraper-config.json
      # CI更新
      - .github/workflows/build-search-index.yml

jobs:
  scrape-and-build-search-index:
    runs-on: ubuntu-latest
    steps:
      # wait cloudflare pages publish
      #- run: sleep 2m
      - uses: actions/checkout@v3
      - name: Run docs-scraper
        env:
          HOST_URL: ${{ secrets.MEILISEARCH_HOST }}
          API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
          CONFIG_FILE_PATH: ${{ github.workspace }}/meilisearch-docs-scraper-config.json
        run: |
          docker run -t --rm \
            -e MEILISEARCH_HOST_URL=$HOST_URL \
            -e MEILISEARCH_API_KEY=$API_KEY \
            -v $CONFIG_FILE_PATH:/docs-scraper/config.json \
            getmeili/docs-scraper:v0.12.12 pipenv run ./docs_scraper config.json